# Permalinks
permalink:   pretty

# Settings
markdown:    kramdown
destination: ./_gh_pages
exclude:     ["README.md"]
paginate:    5
encoding:    UTF-8
future:      false
name:        Odin Expo
url:         https://wpbrasil.github.io/odin-expo
description: "Projetos desenvolvidos com Odin Framework"